export const SAVE_INSTANCE = "SAVE_INSTANCE";
export const REMOVE_INSTANCE = "REMOVE_INSTANCE";
export const UPDATE_INSTANCE = "UPDATE_INSTANCE";
export const SAVE_ALL_INSTANCES = "SAVE_ALL_INSTANCES";
export const DELETE_ALL_INSTANCES = "DELETE_ALL_INSTANCES";
export const INVALID_INSTANCE_CANNOT_SAVE = "INVALID_INSTANCE_CANNOT_SAVE";
